### ISSUE TITLE
file path formatting 

### ISSUE THREAD

**Issue by asherif96** [phys201/extended-beam-modeling#12]
I imagine that this file path might cause an issue for Windows users: 

`tod_full, scans, det_info = xb.io.load_tod_file("xbmodeling/input_data/bicepkeck_tods/20150531C01_dk068_tod_singlepair.mat")`

(I didn't have issues but I'm on a Mac.)

**Comment by jacornelison** [comment]
Python is pretty flexible with paths across OS's. I was able to run the `io.py`  code without issue on my Windows machine.
