### ISSUE TITLE
could config.py file be replaced by another kind of object? 

### ISSUE THREAD

**Issue by asherif96** [phys201/extended-beam-modeling#15]
I like the idea of defining a bunch of constants in one file, but it seems like users might need to change certain constants, or add details about another instrument that is not included. Is there a way to define a class so that this is easier? 

I imagine that a Pandas df might be nice, but I'm sure there are many other ways

**Comment by jacornelison** [comment]
All of the mount parameters are hard-coded and unique to each experiment. At some point it may be useful to convert to a Pandas df if we end up with a large repository of experiments, but I think python's dictionary object is sufficient for this purpose for now.
