### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by jennmcguire** [phys201/extended-beam-modeling#19]
This has already been addressed in issue #9. However, it affects more than just the tutorial, so I'm opening a separate issue to emphasize that. Because of the healpy package not being compatible with Windows, the tests fail, meaning that the code itself isn't really being tested.

**Comment by jacornelison** [comment]
I think this is redundant to #9. Testing the module requires testing the functionality of `healpy` which is incompatible with Windows. I've added a disclaimer to the readme warning as such.
