### ISSUE TITLE
Model object doesn't keep track of the right information

### ISSUE THREAD

**Issue by barkls** [phys201/extended-beam-modeling#21]
Right now your `Model` object is defined with a set of parameters describing a beam that is convolved with maps. Then to do a calculation, you pass information about the specific observation you want to model and the `Model` object figures out the intensity measured as a function of time based on the orientation of the telescope.

For an inference calculation the observation is fixed but the beam parameters are varied. Really your model should precalculate orientation map indices on instantiation. When the model is called, it should take beam parameters as arguments and then calculate a convolution, ideally only at the locations of that are relevant to the specific tag being modeled.

**Comment by jacornelison** [comment]
This issue was addressed #32. Data is now fed to the model and map indices are calcuated on instantiation. While this slightly speeds up the creation of simulations, I agree it would definitely be worth trying to reduce the region that gets convolved in future work.
