### ISSUE TITLE
Consider combining notebooks

### ISSUE THREAD

**Issue by barkls** [phys201/extended-beam-modeling#30]
You have a couple different notebooks right now. I think you can get rid of the "model_test" notebook by condensing some of the derivations and removing repeated information. Ideally you will end up with a single notebook, tutorial.ipynb to introduce users to your package.

**Comment by jacornelison** [comment]
A condensed version of the derivations from `model_test` have been added to the tutorial. `model_test` is still proving to be a useful testbed for the model, but I'll remove it when we're confident the model is finalized.
