### ISSUE TITLE
tutorial.ipynb is blank

### ISSUE THREAD

**Issue by jennmcguire** [phys201/extended-beam-modeling#7]
It appears your tutorial content is actually under your "model_test" file instead of your "tutorial" file. Anyone new to your code would be more likely to go to "tutorial" first to understand how to use your model, so the fact that it is currently blank is confusing.

**Comment by jacornelison** [comment]
Thanks. The model is quite complex and was the primary focus of development. Much of the aspects of the model seemed too detailed to be included in the tutorial. Now that everything is up and running, the tutorial has been updated.
