### ISSUE TITLE
Can't run tutorial

### ISSUE THREAD

**Issue by fungfrankie** [phys201/extended-beam-modeling#9]
May be not an issue with the package itself, but I'm opening this to note that I can't run the tutorial to test things out because healpy doesn't work on Windows.

**Comment by jennmcguire** [comment]
I also can't run any of the tutorial due to this issue, and none of the tests can be run on my computer because of it too.

**Comment by jacornelison** [comment]
Apologies. It definitely would've saved you all some time if we had included that `healpy` is incompatible with Windows. As a Windows user myself, my solution to running the code has been to do so through the Odyssey (or I guess now Cannon) cluster. I've updated the readme with a disclaimer.
